insert into market_items (id, kind, name, unit, is_event, sort_order) values
  ('mc4', 'carnes', 'COSTILLA RES T*80gr', 'Porcion', false, 4),
  ('mc5', 'carnes', 'CARNE MOLIDA 90/10', 'Kilo', false, 5),
  ('mc6', 'carnes', 'CARNE GOULASH', 'Kilo', false, 6),
  ('mc7', 'carnes', 'CARNE DESMECHAR (POSTA)', 'Kilo', false, 7),
  ('mc8', 'carnes', 'SOBREBARRIGA PORCIONADA', 'Porcion', false, 8),
  ('mc9', 'carnes', 'HIGADO PORCIONADO', 'Porcion', false, 9),
  ('mc10', 'carnes', 'CALLO PICADO', 'Kilo', false, 10),
  ('mc11', 'carnes', 'BOFE', 'Kilo', false, 11),
  ('mc12', 'carnes', 'CERDO PULPA PORCIONADO', 'Porcion', false, 12),
  ('mc13', 'carnes', 'COSTILLA DE CERDO SL', 'Kilo', false, 13),
  ('mc14', 'carnes', 'MOLIDA DE CERDO', 'Kilo', false, 14),
  ('mc15', 'carnes', 'CERDO BRAZO JULIANA', 'Kilo', false, 15),
  ('mc16', 'carnes', 'CERDO BRAZO GOULASH', 'Kilo', false, 16),
  ('mc17', 'carnes', 'PECHUGA ENTERA', 'Kilo', false, 17),
  ('mc18', 'carnes', 'FILETE PECHUGA PORCIONADA', 'Porcion', false, 18),
  ('mc19', 'carnes', 'FILETE PECHUGA PORCIONADA*60gr', 'Porcion', false, 19),
  ('mc20', 'carnes', 'CORAZONES DE POLLO', 'Kilo', false, 20),
  ('mc21', 'carnes', 'COLOMBINA POLLO', 'Porcion', false, 21),
  ('mc22', 'carnes', 'CONTRAMUSLO POLLO', 'Porcion', false, 22),
  ('mc23', 'carnes', 'FILETE PESCADO', 'Porcion', false, 23),
  ('mc24', 'carnes', 'PESCADO APANADO', 'Bandeja', false, 24),
  ('mc25', 'carnes', 'HUESO RES POROSO', 'Kilo', false, 25),
  ('mc26', 'carnes', 'PATA DE RES PICADA', 'Kilo', false, 26),
  ('mc27', 'carnes', 'PEZUÑA', 'Kilo', false, 27),
  ('mc28', 'carnes', 'RECORTE DE CHARCUTERIA (EVENTO)', 'Kilo', true, 28),
  ('mc29', 'carnes', 'HAMBURGUESA 100gr (EVENTO)', 'UNIDAD', true, 29),
  ('mc30', 'carnes', 'JAMON SANDUCHE (EVENTO)', 'Kilo', true, 30),
  ('mc31', 'carnes', 'SALCHICHA PERRO (EVENTO)', 'Kilo', true, 31),
  ('mc32', 'carnes', 'CHORIZO *430gr (EVENTO)', 'Paq', true, 32),
  ('mc33', 'carnes', 'ENVUELTO*5', 'Paq', false, 33),
  ('mc34', 'carnes', 'AREPA OBLEA*5', 'Paq', false, 34),
  ('mc35', 'carnes', 'AREPA DE CHOCLO*5', 'Paq', false, 35),
  ('ma1', 'abarrotes', 'ACEITE DE OLIVA *1000ML', 'UNID', false, 1),
  ('ma2', 'abarrotes', 'ACEITE SOLISOYA *1000ML', 'UNID', false, 2),
  ('ma3', 'abarrotes', 'AJONJOLI', 'PAQ', false, 3),
  ('ma4', 'abarrotes', 'ALMENDRA BOLSA *500GRS', 'UNID', false, 4),
  ('ma5', 'abarrotes', 'ARROZ BLANCO LIBRA', 'LIBRA', false, 5),
  ('ma6', 'abarrotes', 'ANIS ESTRELLA *250', 'PAQ', false, 6),
  ('ma7', 'abarrotes', 'ARVEJA VERDE LIBRA', 'LIBRA', false, 7),
  ('ma8', 'abarrotes', 'ARVEJA AMARILLA LIBRA', 'LIBRA', false, 8),
  ('ma9', 'abarrotes', 'ATUN EN ACEITE *175GR', 'LATA', false, 9),
  ('ma10', 'abarrotes', 'AVENA HOJUELA PANCHO *180GR', 'PAQ', false, 10),
  ('ma11', 'abarrotes', 'AVENA MOLIDA LA ABUELA *200GR', 'PAQ', false, 11),
  ('ma12', 'abarrotes', 'AZUCAR BLANCO LIBRA', 'LIBRA', false, 12),
  ('ma13', 'abarrotes', 'CAFÉ *500GR', 'LIBRA', false, 13),
  ('ma14', 'abarrotes', 'CANELA EN ASTILLA', 'KILO', false, 14),
  ('ma15', 'abarrotes', 'CEBADA PERLADA *500 GRS', 'LIBRA', false, 15),
  ('ma16', 'abarrotes', 'CEREAL HOJUELA SIN AZUCAR *500GR (NUTRIGAL)', 'KILO', false, 16),
  ('ma17', 'abarrotes', 'CHOCOLATE ESPECIAL *500GR', 'LIBRA', false, 17),
  ('ma18', 'abarrotes', 'CLAVO DE OLOR *500GRS', 'LIBRA', false, 18),
  ('ma19', 'abarrotes', 'COCO DESHIDRATADO *1000GR', 'KILO', false, 19),
  ('ma20', 'abarrotes', 'COCOA *230 GR', 'PAQ', false, 20),
  ('ma21', 'abarrotes', 'CUCHUCO DE CEBADA *500GR', 'LIBRA', false, 21),
  ('ma22', 'abarrotes', 'CURCUMA *500GR', 'PAQ', false, 22),
  ('ma23', 'abarrotes', 'ESENCIA SABORES *500ML', 'UNID', false, 23),
  ('ma24', 'abarrotes', 'ESENCIA VAINILLA NEGRA *500', 'UNID', false, 24),
  ('ma25', 'abarrotes', 'FRIJOL BLANQUILLO *500GR', 'LIBRA', false, 25),
  ('ma26', 'abarrotes', 'FRIJOL BOLA ROJA DESPENSA*500GR', 'LIBRA', false, 26),
  ('ma27', 'abarrotes', 'GALLETA CLUB SOCIAL *9', 'PAQ', false, 27),
  ('ma28', 'abarrotes', 'GALLETA CRAQUEÑA MIEL *10', 'PAQ', false, 28)
on conflict (id) do update
  set kind = excluded.kind, name = excluded.name, unit = excluded.unit,
      is_event = excluded.is_event, sort_order = excluded.sort_order;
