insert into market_items (id, kind, name, unit, is_event, sort_order) values
  ('ms9', 'aseo', 'CEPILLO PARA LAVAR ROPA CERDAS DURAS', 'UND', false, 9),
  ('ms10', 'aseo', 'CHUPA DE BAÑO', 'UND', false, 10),
  ('ms11', 'aseo', 'CHURRUSCO PARA BAÑO CON BASE 1A', 'UND', false, 11),
  ('ms12', 'aseo', 'DESENGRASANTE GALON 4.000ML CLEAN-PRO', 'UND', false, 12),
  ('ms13', 'aseo', 'DESENGRASANTE 500ML CLEAN-PRO', 'UND', false, 13),
  ('ms14', 'aseo', '[object Object]', 'UND', false, 14),
  ('ms15', 'aseo', 'DETERG LIQUIDO MULTIUSOS PH NEUTRO GAL 4.000ml CLEAN-PRO', 'UND', false, 15),
  ('ms16', 'aseo', 'DETERGENTE LAVADORA FRAGANCIA MANZANA O TALCO BB 5 LITROS', 'UND', false, 16),
  ('ms17', 'aseo', 'ENCENDEDOR', 'UND', false, 17),
  ('ms18', 'aseo', 'ESCOBA DURA TR SIN CABO', 'UND', false, 18),
  ('ms19', 'aseo', 'ESCOBA SUAVE SIN CABO', 'UND', false, 19),
  ('ms20', 'aseo', 'ESPONJA DE ALAMBRE ACERO MATRIX - CLOVER', 'UND', false, 20),
  ('ms21', 'aseo', 'ESPONJA ORO /PLATA UND', 'UND', false, 21),
  ('ms22', 'aseo', 'ESPONJILLON DE BRILLO GOL PQ *12', 'UND', false, 22),
  ('ms23', 'aseo', 'FOSFORO MADERA BENGALA CJA *200UNDS', 'UND', false, 23),
  ('ms24', 'aseo', 'GEL ANTIBACTERIAL 1.000ML CON VALVULA DISPENSADORA', 'UND', false, 24),
  ('ms25', 'aseo', 'GUANTE AMARILLO CAL 20 TALLA 8', 'UND', false, 25),
  ('ms26', 'aseo', 'GUANTE DE MANIPULACION PQ *100', 'UND', false, 26),
  ('ms27', 'aseo', 'GUANTE NEGRO TALLA 8 CAL 35', 'UND', false, 27),
  ('ms28', 'aseo', 'JABON EN BARRA DADO *500GR', 'UND', false, 28),
  ('ms29', 'aseo', 'JABON EN BARRA REY UND', 'UND', false, 29),
  ('ms30', 'aseo', '[object Object]', 'UND', false, 30),
  ('ms31', 'aseo', '[object Object]', 'UND', false, 31),
  ('ms32', 'aseo', 'JABON POLVO CLEAN-PRO x 1.000 grms', 'UND', false, 32),
  ('ms33', 'aseo', 'JABON POLVO CLEAN-PRO x 500 grms', 'UND', false, 33),
  ('ms34', 'aseo', 'LIMPIA PISOS DESINFECTANTE CON (FRAGANCIAS CITRONELA, CANELA O LAVANDA)4.000ml', 'UND', false, 34),
  ('ms35', 'aseo', '[object Object]', 'UND', false, 35),
  ('ms36', 'aseo', 'LUSTRA MUEBLE LITRO', 'UND', false, 36),
  ('ms37', 'aseo', 'NEUTRALIZADOR DE OLORES GAL 4.000l CLEAN-PRO', 'UND', false, 37),
  ('ms38', 'aseo', 'PAÑO ABSORVENTE REUTILIZABLE PAQ 4U*25Cms (1METRO)', 'UND', false, 38),
  ('ms39', 'aseo', 'PAPEL ALUMINIO *40 MTS', 'UND', false, 39),
  ('ms40', 'aseo', 'PAPEL HIGIENICO ELITE DUO AMARILLO *UND', 'UND', false, 40),
  ('ms41', 'aseo', 'PAPEL HIGIENICO INDUSTRIAL 250 MTS POR ROLLO', 'UND', false, 41),
  ('ms42', 'aseo', 'PAPEL HIGIENICO INDUSTRIAL *4 *250 MTS BLANCO', 'UND', false, 42),
  ('ms43', 'aseo', 'RECOGEDOR PLASTICO', 'UND', false, 43),
  ('ms44', 'aseo', 'SABRA VERDE GOL UND', 'UND', false, 44),
  ('ms45', 'aseo', 'SELLANTE ANTIDESLIZANTE PARA PISOS 1.000ml', 'UND', false, 45),
  ('ms46', 'aseo', 'SERVILLETA ELITE PAQx100H', 'UND', false, 46),
  ('ms47', 'aseo', 'SUAVIZANTE FRAGANCIA CLEAN-PRO GALON 4LITROS', 'UND', false, 47),
  ('ms48', 'aseo', 'TOALLA COCINA FAVORITA PAQ*3 ROLLOS', 'UND', false, 48),
  ('ms49', 'aseo', 'TOALLAS DE COCINA SCOTT ROLLO REUTILIZABLE', 'UND', false, 49),
  ('ms50', 'aseo', 'TOALLA EN Z PARA MANOS NATURAL PAQx150', 'UND', false, 50),
  ('ms51', 'aseo', 'TOALLA PARA MANOS EN ROLLO ELITE X100mts COLOR NATURAL', 'UND', false, 51),
  ('ms52', 'aseo', 'TRAPERO DE COPA 1A REF800', 'UND', false, 52),
  ('ms53', 'aseo', 'VINIPEL ALIMENTO *300 MTS', 'UND', false, 53)
on conflict (id) do update
  set kind = excluded.kind, name = excluded.name, unit = excluded.unit,
      is_event = excluded.is_event, sort_order = excluded.sort_order;
