insert into market_items (id, kind, name, unit, is_event, sort_order) values
  ('ma29', 'abarrotes', 'GALLETA CRAQUEÑA SALTIN *8', 'PAQ', false, 29),
  ('ma30', 'abarrotes', 'GALLETA DUCALES *9', 'PAQ', false, 30),
  ('ma31', 'abarrotes', 'GALLETA DUCALES 2 TACOS', 'PAQ', false, 31),
  ('ma32', 'abarrotes', 'GALLETA LECHE MUU *18', 'PAQ', false, 32),
  ('ma33', 'abarrotes', 'GALLETA RAMO LECHERITA *8', 'PAQ', false, 33),
  ('ma34', 'abarrotes', 'GALLETA RAMO LIMON *8', 'PAQ', false, 34),
  ('ma35', 'abarrotes', 'GALLETA SALTIN NOEL 3 TACOS', 'PAQ', false, 35),
  ('ma36', 'abarrotes', 'GALLETAS DUX *9', 'PAQ', false, 36),
  ('ma37', 'abarrotes', 'GARBANZO DESPENSA *500GR', 'LIBRA', false, 37),
  ('ma38', 'abarrotes', 'GELATINA GELYFRUTS*500GR', 'PAQ', false, 38),
  ('ma39', 'abarrotes', 'GELATINA SIN SABOR*500GR', 'LIBRA', false, 39),
  ('ma40', 'abarrotes', 'GRANOLA*500 SIN AZUCAR', 'PAQ', false, 40),
  ('ma41', 'abarrotes', 'HARINA PAN AREPA *500GR', 'LIBRA', false, 41),
  ('ma42', 'abarrotes', 'HARINA TRIGO HAZ OROS POLVO HORNEAR *500GR', 'LIBRA', false, 42),
  ('ma43', 'abarrotes', 'KOLA GRANULADA', 'PAQ', false, 43),
  ('ma44', 'abarrotes', 'LECHE PROLECHE ENTERA*900GR', 'PAQ', false, 44),
  ('ma45', 'abarrotes', 'LECHE PROLECHE BOLSA *380 GR', 'PAQ', false, 45),
  ('ma46', 'abarrotes', 'LENTEJA DESPENSA *500GR', 'LIBRA', false, 46),
  ('ma47', 'abarrotes', 'LINAZA EN PEPA *500 GRS', 'LIBRA', false, 47),
  ('ma48', 'abarrotes', 'LINAZA MOLIDA *500 GRS', 'LIBRA', false, 48),
  ('ma49', 'abarrotes', 'MAIZ PETO LIBRA', 'LIBRA', false, 49),
  ('ma50', 'abarrotes', 'MAIZ PIRA LIBRA', 'LIBRA', false, 50),
  ('ma51', 'abarrotes', 'MAIZ TIERNO LATA *432GR (EVENTO)', 'LATA', true, 51),
  ('ma52', 'abarrotes', 'MAIZENA FECULA *380 GR', 'CAJA', false, 52),
  ('ma53', 'abarrotes', 'MANI NATURAL', 'LIBRA', false, 53),
  ('ma54', 'abarrotes', 'MARGARINA CAMPI *250GR', 'UNID', false, 54),
  ('ma55', 'abarrotes', 'MARGARINA LA FINA *500GR', 'UNID', false, 55),
  ('ma56', 'abarrotes', 'MIEL BOTELLA *1000', 'BOTELLA', false, 56),
  ('ma57', 'abarrotes', 'MIGA DE PAN', 'PAQ', false, 57),
  ('ma58', 'abarrotes', 'NUEZ ALFA LIBRA', 'PAQ', false, 58),
  ('ma59', 'abarrotes', 'NUEZ MOSCADA *500GR', 'PAQ', false, 59),
  ('ma60', 'abarrotes', 'PANELA BOLSA 450 GRS', 'UNID', false, 60),
  ('ma61', 'abarrotes', 'PAPRIKA *500 GRS', 'LIBRA', false, 61),
  ('ma62', 'abarrotes', 'PASTA LA NIEVE CONCHA *250GR', 'PAQ', false, 62),
  ('ma63', 'abarrotes', 'PASTA LA NIEVE FIDEOS *250GR', 'PAQ', false, 63),
  ('ma64', 'abarrotes', 'PASTA DORIA TORNILLOS *250GR', 'PAQ', false, 64),
  ('ma65', 'abarrotes', 'PASTA LASAÑA DORIA *400GR', 'LIBRA', false, 65),
  ('ma66', 'abarrotes', 'PASTA MACARRONES*250GR', 'LIBRA', false, 66),
  ('ma67', 'abarrotes', 'PASTA LA NIEVE SPAGUETTI *500GR', 'LIBRA', false, 67),
  ('ma68', 'abarrotes', 'PIMIENTA MOLIDA *500 GRS', 'LIBRA', false, 68),
  ('ma69', 'abarrotes', 'PIMIENTA PEPA *500 GRS', 'LIBRA', false, 69),
  ('ma70', 'abarrotes', 'POLVO HORNEAR', 'UNID', false, 70),
  ('ma71', 'abarrotes', 'PONQUE RAMITO *10', 'PAQ', false, 71),
  ('ma72', 'abarrotes', 'PUDIN SABOR*500GR (evento)', 'LIBRA', true, 72),
  ('ma73', 'abarrotes', 'QUINUA BOLSA *500GRS', 'PAQ', false, 73),
  ('ma74', 'abarrotes', 'SAL *1000GR', 'KILO', false, 74),
  ('ma75', 'abarrotes', 'SALSA SOYA *1000ML', 'BOTELLA', false, 75),
  ('ma76', 'abarrotes', 'SARDINA EN SALSA DE TOMATE *425GR', 'LATA', false, 76),
  ('ma77', 'abarrotes', 'TE', 'CAJA', false, 77),
  ('ma78', 'abarrotes', 'UVA PASA', 'LIBRA', false, 78),
  ('ma79', 'abarrotes', 'VINAGRE FRASCO *500ML', 'BOTELLA', false, 79),
  ('ma80', 'abarrotes', 'CARVE *200 GRS', 'BOLSA', false, 80),
  ('ms1', 'aseo', 'BAYETILLA DE 100x70CM', 'UND', false, 1),
  ('ms2', 'aseo', '[object Object]', 'UND', false, 2),
  ('ms3', 'aseo', 'BOLSA BASURA BLANCA 70*100 X 10 UND', 'UND', false, 3),
  ('ms4', 'aseo', 'BOLSA BASURA BLANCA PAPELERA 40*60*10', 'UND', false, 4),
  ('ms5', 'aseo', 'BOLSA BASURA NEGRA PAPELERA 40*60*10', 'UND', false, 5),
  ('ms6', 'aseo', 'BOLSA BASURA NEGRA 70*100 X 10 UND', 'UND', false, 6),
  ('ms7', 'aseo', 'BOLSA BASURA VERDE 70*100 X 10 UND', 'UND', false, 7),
  ('ms8', 'aseo', 'CABO METALICO 120CM ALTA RESISTENCIA', 'UND', false, 8)
on conflict (id) do update
  set kind = excluded.kind, name = excluded.name, unit = excluded.unit,
      is_event = excluded.is_event, sort_order = excluded.sort_order;
