insert into market_items (id, kind, name, unit, is_event, sort_order) values
  ('mf61', 'fruver', 'MANZANA GALA', 'KG', false, 61),
  ('mf62', 'fruver', 'MANZANA VERDE', 'KG', false, 62),
  ('mf63', 'fruver', 'MARACUYA', 'KG', false, 63),
  ('mf64', 'fruver', 'MAZORCA DESGRANADA', 'KG', false, 64),
  ('mf65', 'fruver', 'MAZORCA TUZA', 'KG', false, 65),
  ('mf66', 'fruver', 'MELÓN', 'KG', false, 66),
  ('mf67', 'fruver', 'MORA', 'KG', false, 67),
  ('mf68', 'fruver', 'MUTE', 'KG', false, 68),
  ('mf69', 'fruver', 'NARANJA TANGELO', 'KG', false, 69),
  ('mf70', 'fruver', 'NARANJA VALENCIA', 'KG', false, 70),
  ('mf71', 'fruver', 'OREGANO', 'ATAO', false, 71),
  ('mf72', 'fruver', 'PAPA CRIOLLA LAVADA', 'KG', false, 72),
  ('mf73', 'fruver', 'PAPA PASTUSA', 'KG', false, 73),
  ('mf74', 'fruver', 'PAPA SABANERA', 'KG', false, 74),
  ('mf75', 'fruver', 'PAPAYA MELONA', 'KG', false, 75),
  ('mf76', 'fruver', 'PAPAYUELA', 'KG', false, 76),
  ('mf77', 'fruver', 'PATILLA BABY', 'KG', false, 77),
  ('mf78', 'fruver', 'PEPINO COHOMBRO', 'KG', false, 78),
  ('mf79', 'fruver', 'PEPINO COMÚN', 'KG', false, 79),
  ('mf80', 'fruver', 'PERA NACIONAL', 'KG', false, 80),
  ('mf81', 'fruver', 'PERA VERDE', 'KG', false, 81),
  ('mf82', 'fruver', 'PEREJIL', 'KG', false, 82),
  ('mf83', 'fruver', 'PIMENTÓN ROJO', 'KG', false, 83),
  ('mf84', 'fruver', 'PIMENTÓN VERDE', 'KG', false, 84),
  ('mf85', 'fruver', 'PIÑA GOLDEN', 'KG', false, 85),
  ('mf86', 'fruver', 'PIÑA PEROLERA', 'KG', false, 86),
  ('mf87', 'fruver', 'PLÁTANO MADURO', 'KG', false, 87),
  ('mf88', 'fruver', 'PLÁTANO VERDE', 'KG', false, 88),
  ('mf89', 'fruver', 'QUESO CAMPESINO', 'KG', false, 89),
  ('mf90', 'fruver', 'QUESO COSTEÑO', 'KG', false, 90),
  ('mf91', 'fruver', 'QUESO DOBLE CREMA', 'KG', false, 91),
  ('mf92', 'fruver', 'QUESO DOBLE CREMA TAJADO', 'KG', false, 92),
  ('mf93', 'fruver', 'RABANO ROJO', 'KG', false, 93),
  ('mf94', 'fruver', 'RICES CHINAS', 'BAN', false, 94),
  ('mf95', 'fruver', 'REMOLACHA', 'KG', false, 95),
  ('mf96', 'fruver', 'REPOLLO BLANCO', 'KG', false, 96),
  ('mf97', 'fruver', 'REPOLLO MORADO', 'KG', false, 97),
  ('mf98', 'fruver', 'RUGULA', 'ATAO', false, 98),
  ('mf99', 'fruver', 'SABILA', 'UNID', false, 99),
  ('mf100', 'fruver', 'TOMATE ÁRBOL', 'KG', false, 100),
  ('mf101', 'fruver', 'TOMATE CHONTO', 'KG', false, 101),
  ('mf102', 'fruver', 'TOMATE MILANO', 'KG', false, 102),
  ('mf103', 'fruver', 'TORTILLA *10U', 'PAQ', false, 103),
  ('mf104', 'fruver', 'UCHUVA', 'KG', false, 104),
  ('mf105', 'fruver', 'UVA ISABELLA', 'BAN', false, 105),
  ('mf106', 'fruver', 'UVA ROJA IMPORTADA (evento)', 'KG', true, 106),
  ('mf107', 'fruver', 'UVA VERDE NACIONAL', 'KG', false, 107),
  ('mf108', 'fruver', 'YACÓN', 'KG', false, 108),
  ('mf109', 'fruver', 'YOGURT GRIEGO (evento)', 'LT', true, 109),
  ('mf110', 'fruver', 'YOGURTH D1 (evento)', 'UNID', true, 110),
  ('mf111', 'fruver', 'YOGURTH*1000ML', 'LT', false, 111),
  ('mf112', 'fruver', 'YOGURTH*200ML', 'UNID', false, 112),
  ('mf113', 'fruver', 'YUCA', 'KG', false, 113),
  ('mf114', 'fruver', 'ZANAHORIA', 'KG', false, 114),
  ('mf115', 'fruver', 'ZAPOTE', 'KG', false, 115),
  ('mf116', 'fruver', 'ZUQUINI AMARILLO', 'KG', false, 116),
  ('mf117', 'fruver', 'ZUQUINI VERDE', 'KG', false, 117),
  ('mc1', 'carnes', 'CARNE ASAR PORCION', 'Porcion', false, 1),
  ('mc2', 'carnes', 'CARNE SUDAR PORCION', 'Porcion', false, 2),
  ('mc3', 'carnes', 'CARNE SUDAR PORCION x60gr', 'Porcion', false, 3)
on conflict (id) do update
  set kind = excluded.kind, name = excluded.name, unit = excluded.unit,
      is_event = excluded.is_event, sort_order = excluded.sort_order;
