insert into market_items (id, kind, name, unit, is_event, sort_order) values
  ('mf1', 'fruver', 'ACELGA', 'KG', false, 1),
  ('mf2', 'fruver', 'AGUACATE JAZZ', 'KG', false, 2),
  ('mf3', 'fruver', 'AGUACATE PAPELILLO', 'KG', false, 3),
  ('mf4', 'fruver', 'AJO NACIONAL', 'KG', false, 4),
  ('mf5', 'fruver', 'ALBACA', 'ATAO', false, 5),
  ('mf6', 'fruver', 'APIO', 'MATA', false, 6),
  ('mf7', 'fruver', 'ARANDANOS (evento)', 'KG', true, 7),
  ('mf8', 'fruver', 'AROMÁTICAS', 'ATAO', false, 8),
  ('mf9', 'fruver', 'ARRACACHA', 'KG', false, 9),
  ('mf10', 'fruver', 'ARVERJA VERDE DESGRANADA', 'KG', false, 10),
  ('mf11', 'fruver', 'AUYAMA', 'KG', false, 11),
  ('mf12', 'fruver', 'BANANO CRIOLLO', 'KG', false, 12),
  ('mf13', 'fruver', 'BANANO URABA', 'KG', false, 13),
  ('mf14', 'fruver', 'BERENJENA', 'KG', false, 14),
  ('mf15', 'fruver', 'BOLSA KILO Y MEDIO', 'PAQ', false, 15),
  ('mf16', 'fruver', 'BROCOLI', 'KG', false, 16),
  ('mf17', 'fruver', 'CALABACÍN', 'KG', false, 17),
  ('mf18', 'fruver', 'CALABAZA', 'KG', false, 18),
  ('mf19', 'fruver', 'CEBOLLA CABEZONA BLANCA', 'KG', false, 19),
  ('mf20', 'fruver', 'CEBOLLA CABEZONA ROJA', 'KG', false, 20),
  ('mf21', 'fruver', 'CEBOLLA LARGA', 'KG', false, 21),
  ('mf22', 'fruver', 'CHAMPIÑON', 'KG', false, 22),
  ('mf23', 'fruver', 'CILANTRO', 'KG', false, 23),
  ('mf24', 'fruver', 'CIRUELA IMPORTADA', 'KG', false, 24),
  ('mf25', 'fruver', 'CIRUELA NACIONAL', 'KG', false, 25),
  ('mf26', 'fruver', 'COCO', 'UNID', false, 26),
  ('mf27', 'fruver', 'COLICERO', 'KG', false, 27),
  ('mf28', 'fruver', 'COLIFLOR', 'KG', false, 28),
  ('mf29', 'fruver', 'CREMA LECHE', 'KG', false, 29),
  ('mf30', 'fruver', 'CURUBA', 'KG', false, 30),
  ('mf31', 'fruver', 'DURAZNO NACIONAL', 'KG', false, 31),
  ('mf32', 'fruver', 'ESPINACA', 'KG', false, 32),
  ('mf33', 'fruver', 'FEIJOA', 'KG', false, 33),
  ('mf34', 'fruver', 'FRESA GRUESA', 'KG', false, 34),
  ('mf35', 'fruver', 'FRESA MEDIANA', 'KG', false, 35),
  ('mf36', 'fruver', 'GENGIBRE', 'KG', false, 36),
  ('mf37', 'fruver', 'GRANADILLA', 'KG', false, 37),
  ('mf38', 'fruver', 'GUANABANA', 'KG', false, 38),
  ('mf39', 'fruver', 'GUASCAS', 'KG', false, 39),
  ('mf40', 'fruver', 'GUATILA', 'KG', false, 40),
  ('mf41', 'fruver', 'GUAYABA PERA', 'KG', false, 41),
  ('mf42', 'fruver', 'HABICHUELA', 'KG', false, 42),
  ('mf43', 'fruver', 'HIERNABUENA', 'ATAO', false, 43),
  ('mf44', 'fruver', 'HUEVOS AMARILLOS AA*30', 'CUBETA', false, 44),
  ('mf45', 'fruver', 'KIWI', 'KG', false, 45),
  ('mf46', 'fruver', 'KUMIS *200ML', 'UNID', false, 46),
  ('mf47', 'fruver', 'KUMIS*1000ML', 'LT', false, 47),
  ('mf48', 'fruver', 'LAUREL Y TOMILLO', 'ATAO', false, 48),
  ('mf49', 'fruver', 'LECHE DESCREMADA MAXILITRO', 'UND', false, 49),
  ('mf50', 'fruver', 'LECHE DESLACTOSADA MAXILITRO', 'UND', false, 50),
  ('mf51', 'fruver', 'LECHE LARGA VIDA MAXILITRO', 'UND', false, 51),
  ('mf52', 'fruver', 'LECHUGA BATAVIA', 'KG', false, 52),
  ('mf53', 'fruver', 'LECHUGA CRESPA VERDE', 'UND', false, 53),
  ('mf54', 'fruver', 'LIMÓN TAHITI', 'KG', false, 54),
  ('mf55', 'fruver', 'LIMONCILLO', 'ATAO', false, 55),
  ('mf56', 'fruver', 'LULO', 'KG', false, 56),
  ('mf57', 'fruver', 'MANDARINA ARRAYANA', 'KG', false, 57),
  ('mf58', 'fruver', 'MANGO AZUCAR', 'KG', false, 58),
  ('mf59', 'fruver', 'MANGO COMUN', 'KG', false, 59),
  ('mf60', 'fruver', 'MANGO TOMY', 'KG', false, 60)
on conflict (id) do update
  set kind = excluded.kind, name = excluded.name, unit = excluded.unit,
      is_event = excluded.is_event, sort_order = excluded.sort_order;
