-- Migración: categoría FRUTAS Y VERDURAS (fruver), transcrita desde
-- Kardex_Septiembre-hoja2.xlsx y hoja3.xlsx (una sola categoría partida
-- en dos hojas por el tamaño de la foto original). Nombres y unidades
-- se dejan tal como están transcritos del físico, sin corregir posibles
-- errores de escritura a mano (ver hoja 'Notas' de cada archivo).
--
-- Ejecutar una sola vez en el SQL Editor de Supabase, después de haber
-- corrido products.sql (la tabla ya debe existir).

insert into products (id, category, name, unit, min_stock, sort_order) values
  ('p47', 'FRUTAS Y VERDURAS', 'Acelga', 'LIBRA', 5, 47),
  ('p48', 'FRUTAS Y VERDURAS', 'Aguacate jazz', 'UNIDAD', 5, 48),
  ('p49', 'FRUTAS Y VERDURAS', 'Aguacate papelillo', 'UNIDAD', 5, 49),
  ('p50', 'FRUTAS Y VERDURAS', 'Ajo nacional', 'LIBRA', 5, 50),
  ('p51', 'FRUTAS Y VERDURAS', 'Albaca', 'ATAO', 5, 51),
  ('p52', 'FRUTAS Y VERDURAS', 'Apio', 'MATA', 5, 52),
  ('p53', 'FRUTAS Y VERDURAS', 'Arandanos (evento)', 'LIBRA', 5, 53),
  ('p54', 'FRUTAS Y VERDURAS', 'Aromaticas', 'ATAO', 5, 54),
  ('p55', 'FRUTAS Y VERDURAS', 'Arracacha', 'LIBRA', 5, 55),
  ('p56', 'FRUTAS Y VERDURAS', 'Arveja verde desgranada', 'LIBRA', 5, 56),
  ('p57', 'FRUTAS Y VERDURAS', 'Auyama', 'LIBRA', 5, 57),
  ('p58', 'FRUTAS Y VERDURAS', 'Banano criollo', 'UNIDAD', 5, 58),
  ('p59', 'FRUTAS Y VERDURAS', 'Banano uraba', 'UNIDAD', 5, 59),
  ('p60', 'FRUTAS Y VERDURAS', 'Berenjena', 'LIBRA', 5, 60),
  ('p61', 'FRUTAS Y VERDURAS', 'Bolsa kilo y medio', 'PAQUETE', 5, 61),
  ('p62', 'FRUTAS Y VERDURAS', 'Brocoli', 'LIBRA', 5, 62),
  ('p63', 'FRUTAS Y VERDURAS', 'Calabacin', 'LIBRA', 5, 63),
  ('p64', 'FRUTAS Y VERDURAS', 'Calabaza', 'LIBRA', 5, 64),
  ('p65', 'FRUTAS Y VERDURAS', 'Cebolla cabezona blanca', 'UNIDAD', 5, 65),
  ('p66', 'FRUTAS Y VERDURAS', 'Cebolla cabezona roja', 'UNIDAD', 5, 66),
  ('p67', 'FRUTAS Y VERDURAS', 'Cebolla larga', 'LIBRA', 5, 67),
  ('p68', 'FRUTAS Y VERDURAS', 'Champiñon', 'BANDEJA', 5, 68),
  ('p69', 'FRUTAS Y VERDURAS', 'Cilantro', 'LIBRA', 5, 69),
  ('p70', 'FRUTAS Y VERDURAS', 'Ciruela importada', 'UNIDAD', 5, 70),
  ('p71', 'FRUTAS Y VERDURAS', 'Ciruela nacional', 'BANDEJA', 5, 71),
  ('p72', 'FRUTAS Y VERDURAS', 'Coco', 'UNIDAD', 5, 72),
  ('p73', 'FRUTAS Y VERDURAS', 'Colicero', 'LIBRA', 5, 73),
  ('p74', 'FRUTAS Y VERDURAS', 'Coliflor', 'LIBRA', 5, 74),
  ('p75', 'FRUTAS Y VERDURAS', 'Curuba', 'LIBRA', 5, 75),
  ('p76', 'FRUTAS Y VERDURAS', 'Durazno nacional', 'UNIDAD', 5, 76),
  ('p77', 'FRUTAS Y VERDURAS', 'Espinaca', 'LIBRA', 5, 77),
  ('p78', 'FRUTAS Y VERDURAS', 'Feijoa', 'LIBRA', 5, 78),
  ('p79', 'FRUTAS Y VERDURAS', 'Fresa gruesa', 'LIBRA', 5, 79),
  ('p80', 'FRUTAS Y VERDURAS', 'Fresa mediana', 'LIBRA', 5, 80),
  ('p81', 'FRUTAS Y VERDURAS', 'Gengibre', 'LIBRA', 5, 81),
  ('p82', 'FRUTAS Y VERDURAS', 'Granadilla', 'UNIDAD', 5, 82),
  ('p83', 'FRUTAS Y VERDURAS', 'Guanabana', 'LIBRA', 5, 83),
  ('p84', 'FRUTAS Y VERDURAS', 'Guascas', 'ATAO', 5, 84),
  ('p85', 'FRUTAS Y VERDURAS', 'Guatila', 'LIBRA', 5, 85),
  ('p86', 'FRUTAS Y VERDURAS', 'Guayaba pera', 'LIBRA', 5, 86),
  ('p87', 'FRUTAS Y VERDURAS', 'Habicuela', 'LIBRA', 5, 87),
  ('p88', 'FRUTAS Y VERDURAS', 'Hierbabuena', 'LIBRA', 5, 88),
  ('p89', 'FRUTAS Y VERDURAS', 'Kiwi', 'UNIDAD', 5, 89),
  ('p90', 'FRUTAS Y VERDURAS', 'Laurel y tomillo', 'ATAO', 5, 90),
  ('p91', 'FRUTAS Y VERDURAS', 'Lechuga batavia', 'UNIDAD', 5, 91),
  ('p92', 'FRUTAS Y VERDURAS', 'Lechuga crespa verde', 'UNIDAD', 5, 92),
  ('p93', 'FRUTAS Y VERDURAS', 'Loimon tahiti', 'LIBRA', 5, 93),
  ('p94', 'FRUTAS Y VERDURAS', 'Limoncillo', 'ATAO', 5, 94),
  ('p95', 'FRUTAS Y VERDURAS', 'Lulo', 'LIBRA', 5, 95),
  ('p96', 'FRUTAS Y VERDURAS', 'Mandarina arrayana', 'UNIDAD', 5, 96),
  ('p97', 'FRUTAS Y VERDURAS', 'Mango azúcar', 'UNIDAD', 5, 97),
  ('p98', 'FRUTAS Y VERDURAS', 'Mango comun', 'UNIDAD', 5, 98),
  ('p99', 'FRUTAS Y VERDURAS', 'Mango tomy', 'UNIDAD', 5, 99),
  ('p100', 'FRUTAS Y VERDURAS', 'Manzana gala', 'UNIDAD', 5, 100),
  ('p101', 'FRUTAS Y VERDURAS', 'Manzana verde', 'UNIDAD', 5, 101),
  ('p102', 'FRUTAS Y VERDURAS', 'Maracuya', 'LIBRA', 5, 102),
  ('p103', 'FRUTAS Y VERDURAS', 'Mazorca desgranada', 'LIBRA', 5, 103),
  ('p104', 'FRUTAS Y VERDURAS', 'Mazorca tuza', 'LIBRA', 5, 104),
  ('p105', 'FRUTAS Y VERDURAS', 'Melón', 'LIBRA', 5, 105),
  ('p106', 'FRUTAS Y VERDURAS', 'Mora', 'LIBRA', 5, 106),
  ('p107', 'FRUTAS Y VERDURAS', 'Mute', 'PAQUETE', 5, 107),
  ('p108', 'FRUTAS Y VERDURAS', 'Naranja tangelo', 'UNIDAD', 5, 108),
  ('p109', 'FRUTAS Y VERDURAS', 'Naranja valencia', 'UNIDAD', 5, 109),
  ('p110', 'FRUTAS Y VERDURAS', 'Oregano', 'ATAO', 5, 110),
  ('p111', 'FRUTAS Y VERDURAS', 'Papa criolla lavada', 'LIBRA', 5, 111),
  ('p112', 'FRUTAS Y VERDURAS', 'Papa pastusa', 'LIBRA', 5, 112),
  ('p113', 'FRUTAS Y VERDURAS', 'Papa sabanera', 'LIBRA', 5, 113),
  ('p114', 'FRUTAS Y VERDURAS', 'Papaya melona', 'LIBRA', 5, 114),
  ('p115', 'FRUTAS Y VERDURAS', 'Papayuela', 'LIBRA', 5, 115),
  ('p116', 'FRUTAS Y VERDURAS', 'Patilla baby', 'LIBRA', 5, 116),
  ('p117', 'FRUTAS Y VERDURAS', 'Pepino cohombro', 'LIBRA', 5, 117),
  ('p118', 'FRUTAS Y VERDURAS', 'Pepino comun', 'LIBRA', 5, 118),
  ('p119', 'FRUTAS Y VERDURAS', 'Pera nacional', 'UNIDAD', 5, 119),
  ('p120', 'FRUTAS Y VERDURAS', 'Pera verde', 'UNIDAD', 5, 120),
  ('p121', 'FRUTAS Y VERDURAS', 'Perejil', 'LIBRA', 5, 121),
  ('p122', 'FRUTAS Y VERDURAS', 'Pimenton rojo', 'UNIDAD', 5, 122),
  ('p123', 'FRUTAS Y VERDURAS', 'Pimenton verde', 'UNIDAD', 5, 123),
  ('p124', 'FRUTAS Y VERDURAS', 'Piña golden', 'LIBRA', 5, 124),
  ('p125', 'FRUTAS Y VERDURAS', 'Piña perolera', 'LIBRA', 5, 125),
  ('p126', 'FRUTAS Y VERDURAS', 'Platano maduro', 'UNIDAD', 5, 126),
  ('p127', 'FRUTAS Y VERDURAS', 'Platano verde', 'UNIDAD', 5, 127),
  ('p128', 'FRUTAS Y VERDURAS', 'Rabano rojo', 'LIBRA', 5, 128),
  ('p129', 'FRUTAS Y VERDURAS', 'Raices chinas', 'BANDEJA', 5, 129),
  ('p130', 'FRUTAS Y VERDURAS', 'Remolacha', 'LIBRA', 5, 130),
  ('p131', 'FRUTAS Y VERDURAS', 'Repollo blanco', 'LIBRA', 5, 131),
  ('p132', 'FRUTAS Y VERDURAS', 'Repollo morado', 'LIBRA', 5, 132),
  ('p133', 'FRUTAS Y VERDURAS', 'Rugula', 'ATAO', 5, 133),
  ('p134', 'FRUTAS Y VERDURAS', 'Sabila', 'UNIDAD', 5, 134),
  ('p135', 'FRUTAS Y VERDURAS', 'Tomate arbol', 'LIBRA', 5, 135),
  ('p136', 'FRUTAS Y VERDURAS', 'Tomate chonto', 'UNIDAD', 5, 136),
  ('p137', 'FRUTAS Y VERDURAS', 'Tomate milano', 'UNIDAD', 5, 137),
  ('p138', 'FRUTAS Y VERDURAS', 'Uchuva', 'LIBRA', 5, 138),
  ('p139', 'FRUTAS Y VERDURAS', 'Uva isabella', 'BANDEJA', 5, 139),
  ('p140', 'FRUTAS Y VERDURAS', 'Uva roja importada (evento)', 'LIBRA', 5, 140),
  ('p141', 'FRUTAS Y VERDURAS', 'Uva verde nacional', 'LIBRA', 5, 141),
  ('p142', 'FRUTAS Y VERDURAS', 'Yacón', 'LIBRA', 5, 142),
  ('p143', 'FRUTAS Y VERDURAS', 'Yuca', 'LIBRA', 5, 143),
  ('p144', 'FRUTAS Y VERDURAS', 'Zanahoria', 'LIBRA', 5, 144),
  ('p145', 'FRUTAS Y VERDURAS', 'Zapote', 'UNIDAD', 5, 145),
  ('p146', 'FRUTAS Y VERDURAS', 'Zuquini amarillo', 'LIBRA', 5, 146),
  ('p147', 'FRUTAS Y VERDURAS', 'Zuquini verde', 'LIBRA', 5, 147);